api_platform:
  title: 'TaskSphere API'
  version: '1.0.0'

  enable_docs: false
  enable_entrypoint: false
  enable_profiler: false
  enable_re_doc: false
  enable_swagger: false
  enable_swagger_ui: false

  formats:
    json:
      mime_types: ['application/json']

when@dev:
  api_platform:
    enable_docs: true
    enable_entrypoint: true
    enable_profiler: true
    enable_re_doc: false
    enable_swagger: true
    enable_swagger_ui: true

    formats:
      jsonld:
        mime_types: [ 'application/ld+json' ]

      json:
        mime_types: ['application/json']

      html:
        mime_types: ['text/html']